### ISSUE TITLE
Few questions regarding the project

### ISSUE THREAD

**Issue by cjjoel** [cjjoel/neeto-ui-challenge#16]
@yedhink
- Is the login page required? I have removed it for for ease of access.
- I made a custom function to format the date. Should I use moment.js instead?
- Should the "created x hours ago" section on the footer of the note card be functional?
- Should the contacts get an avatar unique to them?

**Comment by yedhink** [comment]
@cjjoel 

> Is the login page required? I have removed it for for ease of access.

No need for login page.

> I made a custom function to format the date. Should I use moment.js instead?

Don't use moment.js. It's deprecated now and also is bulky. Use vanilla JS or use `dayjs`

> Should the "created x hours ago" section on the footer of the note card be functional?

No need.

> Should the contacts get an avatar unique to them?

No need.
